stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: llamallama/send:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./rancher/deployment.yaml
timeout: 60
branch:
  include:
  - master
notification: {}
